  

site_name: knr_at_iaac - documenting my mdef
site_description: reflections on and documentation of my mdef journey
site_author: knr-at-iaac
copyright: Copyleft 2021 "knr-at-iaac" - GNU Free Documentation License
#repo_name: 'knr-at-iaac : MDEF'
site_url: https://knr-at-iaac.github.io/MDEF/
#repo_url: 'https://knr-at-iaac.github.io/MDEF/'


nav:
  - Home: index.md
  

  - Reflections :
      - Term 1:
          - Bootcamp: term1/01-Bootcamp.md
          - AoWS: term1/02-Atlas of Weak Signals.md
          
  - Master project:
      - Initial ideas: project/project.md
      
  - About me: about/me.md

  


theme: 
    name: material
    logo: assets/images/yellowSquare.png
    favicon: assets/images/yellowSquare.png
    custom_dir: overrides
    font: 
        code: Silkscreen
        text: Work Sans
    
    palette:
        scheme: slate
        
        
    
extra_css:
  - stylesheets/extra.css

  
#copied from mdef thing

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed